/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Grafica;

import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author esteb
 */
public class Main_Window extends javax.swing.JFrame {

    /**
     * Creates new form Main_Window
     */
    public Main_Window() {
        this.setResizable(false);
        initComponents();
        
        Icon icon = new ImageIcon("C:\\Users\\esteb\\Documents\\TEC\\Algebra\\Progra_2_Algebra_Primeta_Parte\\src\\good.png");
        lblIcon.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbBaseSelect = new javax.swing.JComboBox<>();
        lblBase = new javax.swing.JLabel();
        lblVectorSelect = new javax.swing.JLabel();
        cmbVectorSelect = new javax.swing.JComboBox<>();
        txtfElem1 = new javax.swing.JTextField();
        txtfElem2 = new javax.swing.JTextField();
        txtfElem3 = new javax.swing.JTextField();
        btnAgregarVector = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaBaseDisplay = new javax.swing.JTextArea();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbBaseSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B1", "B2" }));

        lblBase.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBase.setText("Base:");

        lblVectorSelect.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVectorSelect.setText("Vector:");

        cmbVectorSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V1", "V2", "V3" }));

        txtfElem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfElem1KeyTyped(evt);
            }
        });

        txtfElem2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfElem2KeyTyped(evt);
            }
        });

        txtfElem3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfElem3KeyTyped(evt);
            }
        });

        btnAgregarVector.setText("Agregar");

        txtaBaseDisplay.setColumns(20);
        txtaBaseDisplay.setRows(5);
        jScrollPane1.setViewportView(txtaBaseDisplay);

        lblIcon.setBackground(new java.awt.Color(204, 255, 204));
        lblIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblIcon.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtfElem1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfElem2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfElem3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVectorSelect)
                                .addGap(18, 18, 18)
                                .addComponent(cmbVectorSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBase)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBaseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnAgregarVector)
                        .addGap(18, 18, 18)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBaseSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVectorSelect)
                    .addComponent(cmbVectorSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfElem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfElem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfElem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarVector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfElem1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfElem1KeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c.equals(KeyEvent.VK_BACK_SPACE) || 
                c.equals('.') || c.equals(KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtfElem1KeyTyped

    private void txtfElem2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfElem2KeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c.equals(KeyEvent.VK_BACK_SPACE) || 
                c.equals('.') || c.equals(KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtfElem2KeyTyped

    private void txtfElem3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfElem3KeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c.equals(KeyEvent.VK_BACK_SPACE) || 
                c.equals('.') || c.equals(KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtfElem3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVector;
    private javax.swing.JComboBox<String> cmbBaseSelect;
    private javax.swing.JComboBox<String> cmbVectorSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblVectorSelect;
    private javax.swing.JTextArea txtaBaseDisplay;
    private javax.swing.JTextField txtfElem1;
    private javax.swing.JTextField txtfElem2;
    private javax.swing.JTextField txtfElem3;
    // End of variables declaration//GEN-END:variables
}
